"""Added lives

Revision ID: 3a78a4eaccc6
Revises: be6c7e3e1e0b
Create Date: 2025-10-12 02:25:38.840069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a78a4eaccc6'
down_revision = 'be6c7e3e1e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lives', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lives')

    # ### end Alembic commands ###
